/* eslint-disable no-unused-vars */
export enum Action {
    newLoop = 'New Loop',
    waitingForPlayers = 'Waiting for players',
    join = 'Join',
    create = 'Create',
    register = 'Register',
    ready = 'ready',
    nextTurn = 'nextTurn',
    hit = 'hit',
    victory = 'victory',
    quit = 'quit',
    destroy = 'destroy',
    move = 'move',
    attack = 'attack',
    notifyPlayer = 'notifyPlayer',
    notifyServer = 'notifyServer',
    checkCollision = 'checkCollision',
    collision = 'collision',
    updatePlayerPointerState = 'updatePlayerPointerState',
    updatePlayerPointerPosition = 'updatePlayerPointerPosition',
    activate = 'activate',
    draw = 'draw',
}
