export const playerAId = 'player A'
export const playerBId = 'player B'
export const towerId = 'towerId'
export const robotId = 'robotId'
export const gridId = 'gridId'
export const mainMenuEntityId = 'mainMenu'
export const simpleMatchLobbyEntityId = '0000000000000000000000'
export const players = ['Player A', 'Player B', 'Player C', 'Player D', 'Player E', 'Player F', 'Player G', 'Player H']
export const matchId = 'matchId'
export const gameEntityId = 'gameEntityId'
export const expectedAddedPlayers = ['Player A', 'Player B']
export const expectedStillWaitingPlayers = ['Player C', 'Player D']
